### ISSUE TITLE
make mayday less error prone

### ISSUE THREAD

**Issue by Clopy** [mistio/mist.tests#106]
We need to decouple the mayday alert from the gitlab runner. Things we need to do to achieve that:

- put the script that checks the last builds inside the cronjob script. The cronjob should raise the mayday
- also check for the last succesful build and if that was more than 20 minutes ago, raise a mayday
- check for builds that != succesful instead of ==failed to avoid counting pending and canceled ones

**Comment by ptzianos** [comment]
Fixed by @Clopy
