### ISSUE TITLE
Add refresh or wait for machine tags check in machine feature

### ISSUE THREAD

**Issue by ptzianos** [mistio/mist.tests#17]
Then the "first" machine in the list should have a tag with key "testKey" and value "testValue" # tests/gui/steps/tags.py:77
      Assertion Failed: Machine testlikeapro700 has no tag testKey=testValue

    And I click the button "first"                                                                  # None

This error has been happening occasionally in the machines gui test. What happens is that two tags are added to the machine: {testKey: testValue} and {secTestKey: secTestValue} then the second is deleted and the tests go back to the machines list hoping to see the test machine tagged with the first pair. But that doesn't always happen. There are two possible solutions: one is to refresh the page to force the list to be renewed or to add a waiting period.

**Comment by pchristos** [comment]
Pushed along with the new tag validation API test
